export const IMAGES = {
  iphone16Pro: '/products/iphone-16-pro.png',
  iphone16: '/products/iphone-16.png',
  iphone15: '/products/iphone-15.png',
  iphone15Pro: '/products/iphone-15-pro.png',
  macbookPro: '/products/macbook-pro.png',
  macbookAir: '/products/macbook-air.png',
  macMini: '/products/mac-mini.png',
  ipadPro: '/products/ipad-pro.png',
  ipadAir: '/products/ipad-air.png',
  ipadMini: '/products/ipad-mini.jpg',
  airpodsPro: '/products/airpods-pro.png',
  airpods4: '/products/airpods-4.png',
  appleWatch: '/products/apple-watch.png',
  appleWatchSe: '/products/apple-watch-se.png',
  applePencil: '/products/apple-pencil.png',
  airtag: '/products/airtag.png',
  charger: '/products/charger.png',
  keyboard: '/products/keyboard.png',
  echoPop: '/products/echo-pop.avif',
  echoStudio: '/products/echo-studio.jpg',
  echoDot: '/products/echo-dot.png',
  echoShow5: '/products/echo-show-5.avif',
  echoShow8: '/products/echo-show-8.avif',
  echoSpot: '/products/echo-spot.avif',
  bose: '/products/bose-s1.avif',
  lark: '/products/lark.jpg',
  roku: '/products/roku.avif',
  sonyWh: '/products/sony-wh.avif',
  asusRog: '/products/asus-rog.avif',
  laptopStudio: '/products/laptop-top.jpg',
  msiGaming: '/products/msi-gaming.avif',
  legion: '/products/legion.avif',
  avatars: [
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
  ],
} as const
